
server:
  port: 8010
  compression:
    enabled: true

spring:
  application:
    name: verify-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    favicon:
      enabled: false
    date-format: yyyy-MM-dd HH:mm:ss
    servlet:
      load-on-startup: 1
  profiles:
    active: @profiles.active@